using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;

namespace ReverseCoffee
{
    class DiscordWebhookHandler
    {
        public Uri WebhookUri { get; }

        /// <summary>
        /// Sends a message into a dsicord channel via a webhook.
        /// </summary>
        /// <param name="webhookUri">The Uri generated by discord. Including http / https prefix.</param>
        public DiscordWebhookHandler(string webhookUri)
        {
            this.WebhookUri = new Uri(webhookUri);
        }

        public void SendMessage(string message)
        {
            try
            {
                var httpWebRequest = WebRequest.CreateHttp(WebhookUri);
                httpWebRequest.ContentType = "application/json";
                httpWebRequest.Method = "POST";

                using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
                {
                    string json = Newtonsoft.Json.JsonConvert.SerializeObject(new Dictionary<string, string>
                            {
                                { "content" , message }
                            });

                    streamWriter.Write(json);
                }

                var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();

                using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                {
                    var result = streamReader.ReadToEnd();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error while sending discord webhook:\n" + ex.ToString());
            }
        }
    }
}